#!/bin/bash

# 域名和SSL配置脚本
SERVER_IP="8.155.160.129"
SERVER_USER="root"
SERVER_PASSWORD="alywll123##"
DOMAIN="timelesstrips.cn"

echo "🌐 配置域名和SSL证书..."

echo "📊 检查域名解析..."
echo "域名 $DOMAIN 应该解析到 $SERVER_IP"
echo "当前解析结果："
nslookup $DOMAIN

echo ""
echo "🔧 检查服务器状态..."
sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "systemctl status nginx --no-pager"

echo ""
echo "🌍 检查端口监听..."
sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "netstat -tlnp | grep :80"

echo ""
echo "📝 重要配置步骤："
echo ""
echo "1. 域名解析配置："
echo "   在域名管理后台添加A记录："
echo "   - 主机记录：@ (或留空)"
echo "   - 记录值：$SERVER_IP"
echo "   - 主机记录：www"
echo "   - 记录值：$SERVER_IP"
echo ""
echo "2. 阿里云安全组配置："
echo "   登录阿里云控制台 -> ECS实例 -> 安全组 -> 添加入方向规则："
echo "   - 端口范围：80/80"
echo "   - 授权对象：0.0.0.0/0"
echo "   - 优先级：1"
echo "   - 端口范围：443/443"
echo "   - 授权对象：0.0.0.0/0"
echo "   - 优先级：1"
echo ""
echo "3. 等待域名解析生效（通常需要几分钟到几小时）"
echo ""
echo "4. 域名解析生效后，运行以下命令获取SSL证书："
echo "   sshpass -p \"$SERVER_PASSWORD\" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP \"certbot --nginx -d $DOMAIN -d www.$DOMAIN --non-interactive --agree-tos --email admin@$DOMAIN\""
echo ""
echo "🌐 当前访问地址："
echo "HTTP: http://$SERVER_IP"
echo "域名: http://$DOMAIN (需要解析生效)"
echo "HTTPS: https://$DOMAIN (需要SSL证书)"
echo ""
echo "📁 网站文件："
echo "主页面: http://$SERVER_IP/index.html"
echo "东北呼伦贝尔: http://$SERVER_IP/northeast-hulunbeier-travel.html"
echo "黑龙江深度游: http://$SERVER_IP/heilongjiang-travel-enhanced.html"
echo "东三省7天: http://$SERVER_IP/kmTravel.html"
